USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE PDF_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE PDF_RAG_DB;
CREATE OR REPLACE SCHEMA PDF_RAG_DB.APP;

USE DATABASE PDF_RAG_DB;
USE SCHEMA APP;
USE WAREHOUSE PDF_WH;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;