USE DATABASE PDF_RAG_DB;
USE SCHEMA APP;

-- =========================================================
-- 04. DOCUMENT AND CHUNK TABLES
-- =========================================================
CREATE OR REPLACE TABLE PDF_DOCUMENTS (
  RELATIVE_PATH         STRING PRIMARY KEY,
  SIZE_BYTES            NUMBER,
  LAST_MODIFIED         TIMESTAMP_TZ,
  MD5                   STRING,
  FILE_URL              STRING,
  OCR_TEXT              STRING,
  INGESTED_AT           TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT            TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  IS_ACTIVE             BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE PDF_CHUNKS (
  CHUNK_PK              STRING PRIMARY KEY,
  RELATIVE_PATH         STRING,
  CHUNK_NUM             NUMBER,
  CHUNK_TEXT            STRING,
  LAST_MODIFIED         TIMESTAMP_TZ,
  MD5                   STRING,
  INGESTED_AT           TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
 
CREATE OR REPLACE TABLE PDF_RAG_APP_INSIGHTS (
    EVENT_TS            TIMESTAMP_NTZ      DEFAULT CURRENT_TIMESTAMP(),
    EVENT_DATE          DATE               DEFAULT CURRENT_DATE(),
    SESSION_ID          STRING,
    USER_NAME           STRING,
    QUERY_TEXT          STRING,
    TOP_K               NUMBER,
    RESULT_COUNT        NUMBER,
    SEARCH_REQUEST_ID   STRING,
    FIRST_SOURCE        STRING,
    ANSWER_CHARS        NUMBER
);

CREATE OR REPLACE VIEW PDF_RAG_APP_INSIGHTS_DAILY AS
SELECT
    EVENT_DATE,
    COUNT(*)              AS QUERY_COUNT,
    COUNT(DISTINCT USER_NAME) AS USER_COUNT,
    AVG(RESULT_COUNT)     AS AVG_RESULT_COUNT
FROM PDF_RAG_APP_INSIGHTS
GROUP BY EVENT_DATE
ORDER BY EVENT_DATE;