--SHOW GIT REPOSITORIES;
--SHOW GIT BRANCHES IN GIT REPOSITORY PDF_RAG_DB.APP.MYSNOWREPO;

USE DATABASE PDF_RAG_DB;
USE SCHEMA APP; 
CREATE OR REPLACE STREAMLIT PDF_RAG_APP
  FROM @PDF_RAG_DB.APP.mysnowrepo/branches/poc_rag/poc_rag/
  MAIN_FILE = 'STREAMLIT.MAIN.py'
  QUERY_WAREHOUSE = PDF_WH;

 