CREATE GIT REPOSITORY mysnowrepo 
	ORIGIN = 'https://github.com/Dhanapaal/mysnowrepo.git' 
	API_INTEGRATION = 'MYGITAPIINTEGRATION';
    
    --SHOW GIT REPOSITORIES;
--SHOW GIT BRANCHES IN GIT REPOSITORY PDF_RAG_DB.APP.MYSNOWREPO;

USE DATABASE PDF_RAG_DB;
USE SCHEMA APP; 
DROP STREAMLIT PDF_RAG_APP;
CREATE OR REPLACE STREAMLIT PDF_RAG_APP
  FROM @PDF_RAG_DB.APP.mysnowrepo/branches/main/poc_rag/
  MAIN_FILE = '110.STREAMLIT.MAIN.py'
  QUERY_WAREHOUSE = PDF_WH;
/*
 ALTER STREAMLIT PDF_RAG_APP ADD LIVE VERSION FROM LAST;

 SELECT COUNT(*) FROM PDF_CHUNKS;
SHOW CORTEX SEARCH SERVICES IN SCHEMA PDF_RAG_DB.APP;
ALTER TASK TASK_PROCESS_PDF_DELTAS RESUME;

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE PDF_RAG_DB TO ROLE <user_role>;
GRANT USAGE ON SCHEMA PDF_RAG_DB.APP TO ROLE <user_role>;
GRANT USAGE ON STREAMLIT PDF_RAG_DB.APP.PDF_RAG_APP TO ROLE <user_role>;
GRANT USAGE ON WAREHOUSE PDF_WH TO ROLE <user_role>;

*/